CREATE EXTENSION IF NOT EXISTS pgcrypto;


CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_Admin BOOLEAN DEFAULT FALSE,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE (public_id)
);


CREATE TABLE IF NOT EXISTS keys (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_url VARCHAR(200) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    price INT NOT NULL,
    release_date DATE NOT NULL,
    main_picture_url TEXT NOT NULL,
    developer TEXT NOT NULL,
    publisher TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE (key_url, id)
);

-- Доп. картинки (otherPictures)
CREATE TABLE IF NOT EXISTS key_images (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,

    UNIQUE (key_id, url)
);

CREATE TABLE IF NOT EXISTS operation_systems (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    os VARCHAR(100) NOT NULL,

    PRIMARY KEY (key_id, os)
);

CREATE TABLE IF NOT EXISTS activation_platforms (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    platform VARCHAR(100) NOT NULL,

    PRIMARY KEY (key_id, platform)
);

CREATE TABLE IF NOT EXISTS key_genres (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    genre VARCHAR(100) NOT NULL,

    PRIMARY KEY (key_id, genre)
);

-- Системные требования
CREATE TABLE IF NOT EXISTS key_system_requirements (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    profile TEXT NOT NULL CHECK (profile IN ('minimal', 'recommended')),
    cpu TEXT NOT NULL,
    gpu TEXT NOT NULL,
    ram INT NOT NULL,
    memory INT NOT NULL,

    PRIMARY KEY (key_id, profile)
);


CREATE TABLE IF NOT EXISTS purchases (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    price INT,
    count INT DEFAULT NULL,
    date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    tag VARCHAR(70),
    rating INT NOT NULL,
    date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS support_tickets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(30) NOT NULL CHECK (type IN ('question', 'complaint')),
    category VARCHAR(40) NOT NULL CHECK (category IN ('services-balance', 'subscription', 'get-product', 'payment', 'service', 'other')),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    answer TEXT,
    answered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE (public_id)
);


