CREATE EXTENSION IF NOT EXISTS pgcrypto;


CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_Admin BOOLEAN DEFAULT FALSE,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (public_id)
);


CREATE TABLE IF NOT EXISTS keys (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    name VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,

    price INT NOT NULL CHECK (price >= 0),

    release_date DATE NOT NULL,

    main_picture_url TEXT NOT NULL,
    developer TEXT NOT NULL,
    publisher TEXT NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE (public_id)
);

-- Доп. картинки (otherPictures)
CREATE TABLE IF NOT EXISTS key_images (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    UNIQUE (key_id, url)
);

CREATE TABLE IF NOT EXISTS operation_systems (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    os VARCHAR(100) NOT NULL,
    PRIMARY KEY (key_id, os)
);

CREATE TABLE IF NOT EXISTS activation_platforms (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    platform VARCHAR(100) NOT NULL,
    PRIMARY KEY (key_id, platform)
);

CREATE TABLE IF NOT EXISTS key_genres (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    genre VARCHAR(100) NOT NULL,
    PRIMARY KEY (key_id, genre)
);

-- Системные требования
CREATE TABLE IF NOT EXISTS key_system_requirements (
    key_id INT NOT NULL REFERENCES keys(id) ON DELETE CASCADE,
    profile TEXT NOT NULL CHECK (profile IN ('minimal', 'recommended')),
    cpu TEXT NOT NULL,
    gpu TEXT NOT NULL,
    ram TEXT NOT NULL,
    memory TEXT NOT NULL,
    PRIMARY KEY (key_id, profile)
);
